#!/bin/bash

if [[ "$#" -eq  "0" ]]; then 
	echo "You need to pass [true] if run is in decreased system stats, or [false] if normal run"
	exit 1
else
	if $1 ; then
		system="decreased_system_run"
		. clear_results "decreased"
	else
		system="normal_run"
		. clear_results "normal"
	fi
	if [[ $2 ]]; then
		quiet=$2
	else
		quiet=true
	fi
fi

now_date=$(date +%H%M%S_%d%m%y)

. backup_results $system

cd test_delay
echo "running test_delay"

echo "	No CPU stress"
if $quiet ; then
	. run_test $now_date false > /dev/null
else
	. run_test $now_date false
fi

cp -r results/no_stress_"$now_date"/* ../results_all/"$system"/no_stress/test_delay/.

echo "	CPU stress"
if $quiet ; then
	. run_test $now_date true > /dev/null
else
	. run_test $now_date true
fi

cp -r results/stress_"$now_date"/* ../results_all/"$system"/stress/test_delay/.

cd ../sort_random
echo "running sort_random"

echo "	No CPU stress"
if $quiet ; then
	. run_test $now_date false > /dev/null
else
	. run_test $now_date false
fi

cp -r results/no_stress_"$now_date"/* ../results_all/"$system"/no_stress/sort_random/.

echo "	CPU stress"
if $quiet ; then
	. run_test $now_date true > /dev/null
else
	. run_test $now_date true
fi

cp -r results/stress_"$now_date"/* ../results_all/"$system"/stress/sort_random/.

cd ../sort_decreasing
echo "running sort_decreasing"

echo "	No CPU stress"
if $quiet ; then
	. run_test $now_date false > /dev/null
else
	. run_test $now_date false
fi

cp -r results/no_stress_"$now_date"/* ../results_all/"$system"/no_stress/sort_decreasing/.

echo "	CPU stress"
if $quiet ; then
	. run_test $now_date true > /dev/null
else
	. run_test $now_date true
fi

cp -r results/stress_"$now_date"/* ../results_all/"$system"/stress/sort_decreasing/.

cd ..
