#!/bin/bash

prompt=$0
delay=1000

#dumb_probe=$(sudo perf probe -x test 'main' 2>&1 | tr -d '\n' | awk '{print $4}')
#echo "$0! created $dumb_probe tracepoint"
funcb_probe=$(sudo perf probe -x test 'funcB' 2>&1 | tr -d '\n' | awk '{print $4}')
echo "$0! created $funcb_probe tracepoint"
funcb_ret_probe=$(sudo perf probe -x test 'funcB%return' 2>&1 | tr -d '\n' | awk '{print $4}')
echo "$0! created $funcb_ret_probe tracepoint"

echo "$0# perf record output start"
sudo perf record -g -e $funcb_probe -e $funcb_ret_probe ./test > /dev/null
echo "$0# perf record output end"

filename="perf_test"
if [[ -e $filename ]]; then
	echo "$0! old $filename was deleted"
	rm $filename
fi

echo "$0! dumping Perf data to file"
sudo perf script --ns -F time,event --deltatime > $filename
echo "$0# file $filename creadted"

$(source venv/bin/activate)
echo "$0# ./pps.py output start"
./pps.py -i="$funcb_probe" -t="$funcb_ret_probe" -f $filename -d $delay
echo "$0# ./pps.py output end"

#ign=$(sudo perf probe -d $dumb_probe 2>&1)
#echo "$0! deleted $dumb_probe tracepoint"
ign=$(sudo perf probe -d $funcb_probe 2>&1)
echo "$0! deleted $funcb_probe tracepoint"
ign=$(sudo perf probe -d $funcb_ret_probe 2>&1)
echo "$0! deleted $funcb_ret_probe tracepoint"
